kind: pipeline
type: kubernetes
name: CI/CD for bolg

steps:
  - name: build_dest
    image: node
    commands:
      - npm config set registry https://registry.npm.taobao.org
      - npm install
      - npm run-script build
    when:
      event: [push, tag, deployment]

  - name: publish
    image: plugins/docker
    settings:
      mirror: https://rk0frtcz.mirror.aliyuncs.com
      repo: yinshengphy/blog
      tags: latest
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_passwd
    when:
      event: [push, tag, deployment]

  - name: helm_deploy
    image: bitsbeats/drone-helm3
    settings:
      helm_command: upgrade
      chart: helm/
      release: my-project
      namespace: default
      kube_api_server:
        from_secret: kube_url
      kube_token:
        from_secret: kube_token
      kube_certificate:
        from_secret: kube_certificate