kind: pipeline
type: kubernetes
name: CI/CD for bolg

steps:
  - name: build_dest
    image: node
    commands:
      - npm install
      - npm run-script build
    when:
      event: [push, tag, deployment]

  - name: deploy_production
    image: pelotech/drone-helm3
    settings:
      helm_command: upgrade
      chart: helm/
      release: my-project
      api_server:
        from_secret: kube_url
      kubernetes_token:
        from_secret: kube_token


