kind: pipeline
type: kubernetes
name: CI/CD for bolg

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: npm_build
    image: node
    commands:
#      - npm config set registry https://registry.npm.taobao.org
      - npm config set cache ./.npm-cache --global
      - npm install
      - npm run-script build
    when:
      event: [ push, tag, deployment ]
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: docker_push
    image: plugins/docker
    settings:
      mirror: https://rk0frtcz.mirror.aliyuncs.com
      repo: yinshengphy/blog
      tags: ${DRONE_COMMIT}
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_passwd
    when:
      event: [ push, tag, deployment ]

  - name: helm_deploy
    image: bitsbeats/drone-helm3
    settings:
      #      helm_command: install
      chart: helm/
      release: my-blog
      namespace: default
      #      kubectl config view

      kube_api_server:
        from_secret: kube_url
      #        kubectl get secret kubernetes-dashboard-token-tcdfz -o jsonpath={.data.token} -n kubernetes-dashboard | base64 --decode
      kube_token:
        from_secret: kube_token
      #        kubectl get secret kubernetes- dashboard-token-tcdfz -o jsonpath={.data.ca\\.crt} -n kubernetes-dashboard
      kube_certificate:
        from_secret: kube_certificate
      values:
        - commit_hash=${DRONE_COMMIT}
volumes:
  - name: cache
    host:
      path: /tmp/cache
