apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: yinshengphy-cn-webui
  namespace: blog
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`yinshengphy.cn`)
      kind: Rule
      services:
        - name: yinshengphy-cn
          port: 80
      middlewares:
        - name: redirect-https
          namespace: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: yinshengphy-cn-webui-tls
  namespace: blog
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`yinshengphy.cn`)
      kind: Rule
      services:
        - name: yinshengphy-cn
          port: 80
  tls:
    certResolver: myresolver