apiVersion: v1
kind: Secret
metadata:
  name: guacamole-postgres
  namespace: guacamole
type: Opaque
stringData:
  POSTGRES_DB: guacamole_db
  POSTGRES_USER: guacamole_user
  POSTGRES_PASSWORD: replace-with-a-long-random-password
