apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-web
  namespace: blog
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: blog-rag-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-web
                port:
                  number: 80
