apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-web
  namespace: blog
spec:
  template:
    spec:
      containers:
        - name: runner
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - name: blog-content-source
              mountPath: /deploy/content/posts
      volumes:
        - name: blog-content-source
          persistentVolumeClaim:
            claimName: blog-content-source
